name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir openpyxl

    - name: Lint with Flake8
      run: |
        pip install flake8
        flake8 --exclude=.git,__pycache__,.venv,.eggs,build,dist --max-line-length=88 .

    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests/ -v

    - name: Run the script
      run: |
        python myscript.py
