name: Security Checks and Dependency Updates

on:
  schedule:
    - cron: '0 0 * * *' # This runs the checks every day at midnight

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety

    - name: Run Bandit
      run: bandit -r . -lll || echo "Bandit check completed with potential issues"

    - name: Run Safety
      run: safety check

  dependency-updates:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools

    - name: Compile and Upgrade dependencies
      run: |
        pip-compile --upgrade
        pip-sync
